#!/bin/bash -eu

docker pull majkel/chang-rev-proxy &
rm -rf ~/.puma-dev
brew install puma/puma/puma-dev
if test -f ~/Library/Application\ Support/io.puma.dev/cert.pem; then
  security add-trusted-cert -k login.keychain-db ~/Library/Application\ Support/io.puma.dev/cert.pem
fi

puma-dev -install -install-port 8888

if ! grep -q "hal throwaway" ~/.bashrc; then
  cat <<EOF >> ~/.bashrc
# hal throwaway
if [[ -d ~/hal ]]; then
  complete -F __chang hal
  export PATH="${HOME}/hal:\${PATH}"
fi
EOF
fi

if ! grep -q "hal throwaway" ~/.zshrc; then
  cat <<EOF >> ~/.zshrc
# hal throwaway
if [[ -d ~/hal ]]; then
  if [[ -f /usr/local/share/zsh/site-functions/chang ]]; then
    source /usr/local/share/zsh/site-functions/chang
    complete -F __chang hal
  fi
  export PATH="${HOME}/hal:\${PATH}"
fi
EOF
fi

wait

echo "DONE"