#!/bin/bash -eu

docker pull majkel/chang-rev-proxy
set +e
docker rm -f chang-rev-proxy 2>/dev/null
set -e
rm -rf ~/.puma-dev
if ! which puma-dev; then
  brew install puma/puma/puma-dev
  security add-trusted-cert -k login.keychain-db ~/Library/Application\ Support/io.puma.dev/cert.pem
  sudo puma-dev -setup
fi

puma-dev -install -install-port 8888

