#!/bin/bash -eu

docker pull majkel/chang-rev-proxy
set +e
docker rm -f chang-rev-proxy 2>/dev/null
set -e
rm -rf ~/.puma-dev
if ! which puma-dev; then
  brew install puma/puma/puma-dev
  security add-trusted-cert -k login.keychain-db ~/Library/Application\ Support/io.puma.dev/cert.pem
  sudo puma-dev -setup
fi

puma-dev -install -install-port 8888

if ! grep -q "hal throwaway" ~/.bashrc; then
  cat <<EOF >> ~/.bashrc
# hal throwaway
if [[ -d ~/hal ]]; then
  complete -F __chang hal
  export PATH="${HOME}/hal:\${PATH}"
fi
EOF
fi

if ! grep -q "hal throwaway" ~/.zshrc; then
  cat <<EOF >> ~/.zshrc
# hal throwaway
if [[ -d ~/hal ]]; then
  if [[ -f /usr/local/share/zsh/site-functions/chang ]]; then
    source /usr/local/share/zsh/site-functions/chang
    complete -F __chang hal
  fi
  export PATH="${HOME}/hal:\${PATH}"
fi
EOF
fi

echo "DONE"